ipc = pn
splash =false
wallpaper {
    monitor =   # Leave empty for fallback (applies to all monitors)
    path = /home/tiled/Downloads/ach.webp
    # fit_mode = cover  # Optional: default is cover; options: contain, cover, fill, tile
}

